name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Dependências do Sistema
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3-dev zip unzip libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer Cython virtualenv

      - name: Rodar o Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          export BUILDOZER_ALLOW_KIVY_NEW_DESIGN=1
          # O comando abaixo aceita as licenças e inicia a compilação
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: meu-apk-gerado
          path: bin/*.apk
